### ISSUE TITLE
Not sure how to run tests

### ISSUE THREAD

**Issue by derek-adair** [skoczen/django-ajax-uploader#66]
Maybe its because i'm a bit new to django, but i'm not sure how to run the tests with this project.  When i try python run_tests.py i get this warning:

```
(sandbox)➜  django-ajax-uploader git:(master) python run_tests.py
Traceback (most recent call last):
  File "run_tests.py", line 36, in <module>
    main()
  File "run_tests.py", line 32, in main
    call_command('test', 'ajaxuploader')
  File "/home/derek/Dev/.tools/virtualenv/python/sandbox/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 93, in call_command
    app_name = get_commands()[name]
  File "/home/derek/Dev/.tools/virtualenv/python/sandbox/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/derek/Dev/.tools/virtualenv/python/sandbox/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 73, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/home/derek/Dev/.tools/virtualenv/python/sandbox/local/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/home/derek/Dev/.tools/virtualenv/python/sandbox/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by skoczen** [comment]
Django is typically `manage.py test`

https://docs.djangoproject.com/en/1.7/topics/testing/overview/

Ping if you're running into a bug with ajax-uploader!

**Comment by derek-adair** [comment]
Thanks still figuring out django.
